# Deployment config for dashboards
config:
    language-reportcard:
        layout: metrics-by-project
        config: Dashiki:LanguageReportcard
        piwikHost:
        piwikId:
        hostname: language-reportcard.wmflabs.org
        subfolder:

    language-interlanguage:
        layout: tabs
        config: Dashiki:Interlanguage
        piwikHost:
        piwikId:
        hostname: language-reportcard.wmflabs.org
        subfolder: interlanguage

    language-translations:
        layout: tabs
        config: Dashiki:CX2Translations
        piwikHost:
        piwikId:
        hostname: language-reportcard.wmflabs.org
        subfolder: cx2

    flow-by-wiki:
        layout: metrics-by-project
        config: Dashiki:FlowByWiki
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: beta-enables

    flow-reportcard:
        layout: tabs
        config: Dashiki:FlowReportcard
        piwikHost:
        piwikId:
        hostname: flow-reportcard.wmflabs.org
        subfolder:

    page-creation:
        layout: metrics-by-project
        config: Dashiki:PageCreations
        piwikHost:
        piwikId:
        hostname: page-creation.wmflabs.org
        subfolder:

    notifications:
        layout: metrics-by-project
        config: Dashiki:Notifications
        piwikHost:
        piwikId:
        hostname: edit-analysis.wmflabs.org
        subfolder: notifications

    pingback:
        layout: tabs
        config: Dashiki:Pingback
        piwikHost:
        piwikId:
        hostname: pingback.wmflabs.org
        subfolder:

    wmcs-edits:
        layout: tabs
        config: Dashiki:WMCSEdits
        piwikHost:
        piwikId:
        hostname: wmcs-edits.wmflabs.org
        subfolder:

