# Deployment config for dashboards
config:
    edit-analysis:
        layout: compare
        config: Dashiki:VisualEditorAndWikitext
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: compare

    language-reportcard:
        layout: metrics-by-project
        config: Dashiki:LanguageReportcard
        piwikHost:
        piwikId:
        hostname: language-reportcard.wmflabs.org
        subfolder:

    language-interlanguage:
        layout: tabs
        config: Dashiki:Interlanguage
        piwikHost:
        piwikId:
        hostname: language-reportcard.wmflabs.org
        subfolder: interlanguage

    multimedia-health:
        layout: metrics-by-project
        config: Dashiki:MultimediaHealth
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: multimedia-health

    flow-by-wiki:
        layout: metrics-by-project
        config: Dashiki:FlowByWiki
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: beta-enables

    editor-engagement:
        layout: metrics-by-project
        config: Dashiki:EditorEngagement
        piwikHost: piwik.wikimedia.org
        piwikId: 10
        hostname: edit-analysis.wmflabs.org
        subfolder: editor-engagement

    flow-reportcard:
        layout: tabs
        config: Dashiki:FlowReportcard
        piwikHost:
        piwikId:
        hostname: flow-reportcard.wmflabs.org
        subfolder:

    page-creation:
        layout: metrics-by-project
        config: Dashiki:PageCreations
        piwikHost:
        piwikId:
        hostname: page-creation.wmflabs.org
        subfolder:

    notifications:
        layout: metrics-by-project
        config: Dashiki:Notifications
        piwikHost:
        piwikId:
        hostname: edit-analysis.wmflabs.org
        subfolder: notifications

    pingback:
        layout: tabs
        config: Dashiki:Pingback
        piwikHost:
        piwikId:
        hostname: pingback.wmflabs.org
        subfolder:

